#!/bin/bash

SITE=$(ssh -oStrictHostKeyChecking=no $@ "grep 'SBM_URL = ' /usr/local/cpanel/base/frontend/paper_lantern/r1redirect.php" | awk '{print $3}' | cut -d \" -f 2)
if [[ -z ${SITE} ]]; then
    SITE=$(ssh -oStrictHostKeyChecking=no $@ "grep 'Matched public key' /usr/sbin/r1soft/log/cdp.log" | tail -1 | awk '{print $7}' | cut -d / -f 7 | cut -d \' -f 1)
fi

echo ${SITE} | while read line; do firefox -p work $line >/dev/null 2>&1; done
