#!/bin/bash

ssh -oStrictHostKeyChecking=no $@ 'whmapi1 create_user_session user=root service=whostmgrd locale=en' | grep url | awk '{print $2}' | while read line; do firefox -p work $line >/dev/null 2>&1; done &